In [47]:
import os
import cv2
import numpy as np
import torch
import pandas as pd



In [45]:
# from sklearn.model_selection import train_test_split
# train_df = pd.read_csv('./data/open/train.csv')

# train_data, test_data = train_test_split(train_df, test_size=0.4, random_state=42)
# test_data, valid_data = train_test_split(test_data, test_size=0.5, random_state=42)

# train_data.to_csv('./data/open/train_data.csv')
# test_data.to_csv('./data/open/test_data.csv')
# valid_data.to_csv('./data/open/valid_data.csv')

In [48]:
train_data = pd.read_csv('./data/open/train_data.csv')
test_data = pd.read_csv('./data/open/test_data.csv')
valid_data = pd.read_csv('./data/open/valid_data.csv')

In [80]:
from PIL import Image, ImageFile
import torchvision.transforms as transforms
import torchvision


ImageFile.LOAD_TRUNCATED_IMAGES = True

In [3]:
import torch

a = torchvision.transforms.ToTensor()
c = Image.open('data/open/train/000u6xf6ah.jpg').resize((224, 224))
k = Image.open('data/open/train/0as7wdakkr.jpg').resize((224, 224))


img_list = []
s=a(c)
q = a(k)

img_list.append(s)
img_list.append(q)
torch.stack(img_list, dim=0).shape


torch.Size([2, 3, 224, 224])

# 이미지 경로 설정

In [54]:
train_data[['path', 'extension']] = train_data['img_path'].str.split(".", expand=True)[[1, 2]]
train_data = train_data.drop('img_path', axis=1)
valid_data[['path', 'extension']] = valid_data['img_path'].str.split(".", expand=True)[[1, 2]]
valid_data = valid_data.drop('img_path', axis=1)

In [61]:
train_data

Unnamed: 0    img_name       mos  \
0           60735  gubp008c6g  6.748634   
1           36247  uo7nyjk0q8  4.947712   
2           32522  9253eioziz  6.247335   
3           31185  o94xwnigvh  5.671795   
4           74469  leyknxz72e  5.676364   
...           ...         ...       ...   
44735       37194  69ozfzpls0  5.075000   
44736        6265  0mlwgzv380  5.835341   
44737       54886  yp8upku9tg  5.987342   
44738         860  xpzv31nrrz  5.214984   
44739       15795  t6h0aenet1  4.911475   

                                                comments               path  \
0      so much of your work has a wonderful warm ligh...  /train/gubp008c6g   
1      i can see two or three arguments for this repr...  /train/uo7nyjk0q8   
2                one of the best judi the perfect light!  /train/9253eioziz   
3      a fantastic use of hdr, and an out of this wor...  /train/o94xwnigvh   
4      well, yeah, hes a little obvious , but this is...  /train/leyknxz72e   
...                                                  ...                ...   
44735  very good, the the hard light makes the micros...  /train/69ozfzpls0   
44736  the textures seem very flat like too much nois...  /train/0mlwgzv380   
44737  interesting approach.nice mood created by your...  /train/yp8upku9tg   
44738  im not sure the sepia tone is helping this pic...  /train/xpzv31nrrz   
44739  this just looks underexposed. you need to crea...  /train/t6h0aenet1   

      extension  
0           jpg  
1           jpg  
2           jpg  
3           jpg  
4           jpg  
...         ...  
44735       jpg  
44736       jpg  
44737       jpg  
44738       jpg  
44739       jpg  

[44740 rows x 6 columns]

In [87]:
train_images_filepath = [f"./data/open{data.path}.{data.extension}" for idx, data in train_data.iterrows()]
valid_images_filepath = [f"./data/open{data.path}.{data.extension}" for idx, data in valid_data.iterrows()]
# for idx, data in train_data.iterrows():
#     print(f"{data.path}.{data.extension}")
    

In [77]:
print(len(train_images_filepath))
print(len(valid_data))

44740
14914


In [33]:
# train_dir = './data/open/train/'
# test_dir = './data/open/test/'

In [34]:
# train_images_filepath = [os.path.join(train_dir, f) for f in os.listdir(train_dir)]
# test_images_filepath = [os.path.join(test_dir, f) for f in os.listdir(test_dir)]
# # img_filepaths = train_images_filepath + test_images_filepath
# # correct_images_filepaths = [i for i in img_filepaths if cv2.imread(i) is not None]

In [78]:
train_images_filepath

['./data/open/train/gubp008c6g.jpg',
 './data/open/train/uo7nyjk0q8.jpg',
 './data/open/train/9253eioziz.jpg',
 './data/open/train/o94xwnigvh.jpg',
 './data/open/train/leyknxz72e.jpg',
 './data/open/train/kuvvpzlu4g.jpg',
 './data/open/train/7482cw1cc0.jpg',
 './data/open/train/5i686pp79i.jpg',
 './data/open/train/aevceafgq5.jpg',
 './data/open/train/1lxw4v4pdx.jpg',
 './data/open/train/pnlby0y8aq.jpg',
 './data/open/train/h5kw71u74x.jpg',
 './data/open/train/ircuw9wx1m.jpg',
 './data/open/train/ka7lts5sqo.jpg',
 './data/open/train/pe0db077q9.jpg',
 './data/open/train/xk76871qp9.jpg',
 './data/open/train/djgru5j8pk.jpg',
 './data/open/train/ipycznv21m.jpg',
 './data/open/train/4lj5vzznrg.jpg',
 './data/open/train/m6sywmhxke.jpg',
 './data/open/train/0ui8xj2aox.jpg',
 './data/open/train/bcapvpsugm.jpg',
 './data/open/train/hw5wrqpkx4.jpg',
 './data/open/train/n8tu0toqvx.jpg',
 './data/open/train/yl8ok5vuo6.jpg',
 './data/open/train/v40hv7nx76.jpg',
 './data/open/train/a629igjqd8.jpg',
 

In [85]:
tensor = torchvision.transforms.ToTensor()
p = 'data/open/train/002wkuexwb.jpg'
img = Image.open(p).resize((224, 224)).convert("RGB")
img =tensor(img)
print(img.shape)

rgb = img.mean(dim=(1,2))
std = img.std(dim=(1,2))

print(rgb)
print(std)


torch.Size([3, 224, 224])
tensor([0.3171, 0.5547, 0.2492])
tensor([0.2213, 0.1895, 0.1647])


In [81]:
from util.preprocessing import  get_mea_std
train_RGB, train_STD = get_mea_std(train_images_filepath)



/Users/kim-seung-gyeom/opt/anaconda3/envs/ml/lib/python3.9/site-packages/PIL/TiffImagePlugin.py:858: UserWarning: Truncated File Read
  warnings.warn(str(msg))
/Users/kim-seung-gyeom/opt/anaconda3/envs/ml/lib/python3.9/site-packages/PIL/TiffImagePlugin.py:858: UserWarning: Corrupt EXIF data.  Expecting to read 2 bytes but only got 0. 
  warnings.warn(str(msg))


In [86]:
train_RGB

[tensor([0.8377, 0.8155, 0.7837]),
 tensor([0.7660, 0.7563, 0.7166]),
 tensor([0.5456, 0.4366, 0.3449]),
 tensor([0.5598, 0.4470, 0.4357]),
 tensor([0.6007, 0.3985, 0.4330]),
 tensor([0.0780, 0.0742, 0.0604]),
 tensor([0.5151, 0.3435, 0.2433]),
 tensor([0.4053, 0.4053, 0.4053]),
 tensor([0.5176, 0.4735, 0.3862]),
 tensor([0.0701, 0.0791, 0.1929]),
 tensor([0.6610, 0.5113, 0.4579]),
 tensor([0.3965, 0.1990, 0.0562]),
 tensor([0.2015, 0.2039, 0.2114]),
 tensor([0.2008, 0.2385, 0.2222]),
 tensor([0.1914, 0.2706, 0.1113]),
 tensor([0.1698, 0.1143, 0.0940]),
 tensor([0.5530, 0.5530, 0.5530]),
 tensor([0.4326, 0.3924, 0.3674]),
 tensor([0.4854, 0.4222, 0.4270]),
 tensor([0.3105, 0.2750, 0.2433]),
 tensor([0.3371, 0.3371, 0.3371]),
 tensor([0.2165, 0.1433, 0.2095]),
 tensor([0.2366, 0.0760, 0.0337]),
 tensor([0.5254, 0.5565, 0.4966]),
 tensor([0.3409, 0.3293, 0.3112]),
 tensor([0.7057, 0.4956, 0.4693]),
 tensor([0.1062, 0.0728, 0.5643]),
 tensor([0.3529, 0.3529, 0.3529]),
 tensor([0.3097, 0.2

In [88]:
valid_RGB, valid_STD = get_mea_std(valid_images_filepath)

/Users/kim-seung-gyeom/opt/anaconda3/envs/ml/lib/python3.9/site-packages/PIL/TiffImagePlugin.py:858: UserWarning: Truncated File Read
  warnings.warn(str(msg))


In [93]:
def show_img(index):
    tf = transforms.ToPILImage()
    path = train_images_filepath[index]
    print(path)
    img = Image.open(path).resize((224,224)).convert("RGB")

    tensor = torchvision.transforms.ToTensor()
    img =tensor(img)

    print(img.shape)
    
for index, data in enumerate(train_RGB):
    if len(data) == 1:
        show_img(index)
        break

In [95]:
from util.preprocessing import get_channel_mean, get_channel_std

In [96]:

train_meanR, train_meanG, train_meanB = get_channel_mean(train_RGB)
valid_meanR, valid_meanG, valid_meanB = get_channel_std(valid_RGB)

train_stdR, train_stdG, train_stdB = get_channel_mean(train_STD)
valid_stdR, valid_stdG, valid_stdB = get_channel_std(valid_STD)



In [97]:
print("훈련 RGB Mean : ", train_meanR, train_meanG, train_meanB)
print("검증 RGB Mean : ", valid_meanR, valid_meanG, valid_meanB )

print("훈련 RGB Std : ", train_stdR, train_stdG, train_stdB)
print("검증 RGB Std : ", valid_stdR, valid_stdG, valid_stdB)

훈련 RGB Mean :  0.4194325 0.3830166 0.3490198
검증 RGB Mean :  0.4170096 0.38036022 0.34702352
훈련 RGB Std :  0.23905228 0.2253936 0.22334467
검증 RGB Std :  0.23896241 0.22566794 0.22329141


In [107]:
import pandas as pd
def get_pandas(col):
    df = pd.DataFrame(columns=col)
    return df

In [103]:
df = pd.DataFrame(columns=['r_mean', 'g_mean', 'b_mean'])

In [104]:
for i, d in enumerate(train_RGB):
    df.loc[i] = d.numpy()
df.to_csv("train_mean.csv")

In [105]:
import pandas as pd

df = pd.DataFrame(columns=['r_std', 'g_std', 'b_std'])

In [106]:
for i, d in enumerate(train_STD):
    df.loc[i] = d.numpy()
df.to_csv("train_std.csv")


In [102]:
df.mean(axis=0)

r_std    0.239052
g_std    0.225392
b_std    0.223345
dtype: float32

In [108]:
import pandas as pd

df = get_pandas(['r_mean', 'g_mean', 'b_mean'])
for i, d in enumerate(valid_RGB):
    df.loc[i] = d.numpy()
df.to_csv("valid_mean.csv")


df= get_pandas(['r_std', 'g_std', 'b_std'])
for i, d in enumerate(valid_STD):
    df.loc[i] = d.numpy()
df.to_csv("valid_std.csv")
